### ISSUE TITLE
`scripts`-folder missing

### ISSUE THREAD

**Issue by rscircus** [qiboteam/qiboedu#2]
It seems a `scripts` (folder/module) is missing or addressed incorrectly:

<img width="785" alt="image" src="https://github.com/qiboteam/qiboedu/assets/1167114/471cc923-fbb1-4d34-a078-1fe46817d9d1">

### Expected behavior in `L_extra_with_n5_too.ipynb` et al.:

- import works

### Current behavior in `L_extra_with_n5_too.ipynb` et al.:

- import fails

**Comment by rscircus** [comment]
OK, it seems the folder `scripts` is present, however, is not found by the notebook.

**Comment by rscircus** [comment]
A solution would be to add a cell with the following content

```python
import sys
sys.path.append('..')
```

to every notebook.

**Comment by MatteoRobbiati** [comment]
> A solution would be to add a cell with the following content
> 
> ```python
> import sys
> sys.path.append('..')
> ```
> 
> to every notebook.

Yes, you are right! Thanks for opening this.

**Comment by MatteoRobbiati** [comment]
This should now be fixed @rscircus :)
I moved the files we need to import to `src/qiboedu/.`, so that now we can just import them for example doing:

```python
from qiboedu.scripts import plotscripts
```

Many thanks for your help!
